# Generated by Django 3.2.12 on 2022-02-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null='empty')),
                ('email', models.CharField(max_length=200, null='empty')),
                ('password', models.TextField(null='empty')),
                ('pwd', models.TextField(null='empty')),
                ('date', models.CharField(max_length=200, null='empty')),
            ],
        ),
        migrations.CreateModel(
            name='employee_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200, null='empty')),
                ('lname', models.CharField(max_length=200, null='empty')),
                ('email', models.CharField(max_length=200, null='empty')),
                ('phone', models.CharField(max_length=200, null='empty')),
                ('dob', models.CharField(max_length=200, null='empty')),
                ('age', models.CharField(max_length=200, null='empty')),
                ('gender', models.CharField(max_length=200, null='empty')),
                ('marital_status', models.CharField(max_length=200, null='empty')),
                ('address', models.TextField(null='empty')),
                ('language', models.TextField(null='empty')),
                ('qalification', models.TextField(null='empty')),
                ('experience', models.TextField(null='empty')),
                ('jobopted', models.TextField(null='empty')),
                ('compknowledge', models.TextField(null='empty')),
                ('resume', models.FileField(null='empty', upload_to='employe_resume')),
                ('date', models.CharField(max_length=200, null='empty')),
            ],
        ),
        migrations.CreateModel(
            name='employer_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(null='empty', upload_to='employer_logo')),
                ('nameorg', models.TextField(null='empty')),
                ('rname', models.CharField(max_length=200, null='empty')),
                ('email', models.CharField(max_length=200, null='empty')),
                ('phone', models.CharField(max_length=200, null='empty')),
                ('phoner', models.CharField(max_length=200, null='empty')),
                ('designation', models.TextField(null='empty')),
                ('address', models.TextField(null='empty')),
                ('website', models.URLField(max_length=500, null='empty')),
                ('job_file', models.FileField(null='empty', upload_to='employer_file')),
                ('date', models.CharField(max_length=200, null='empty')),
            ],
        ),
    ]
