# Generated by Django 3.1.7 on 2022-03-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee_tb_jobfair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null='empty')),
                ('email', models.CharField(max_length=200, null='empty')),
                ('phone', models.CharField(max_length=200, null='empty')),
                ('qualification', models.TextField(null='empty')),
                ('experience', models.CharField(max_length=200, null='empty')),
                ('linkedin', models.TextField(null='empty')),
                ('category', models.TextField(null='empty')),
                ('resume', models.FileField(null='empty', upload_to='employe_resume')),
                ('date', models.CharField(max_length=200, null='empty')),
            ],
        ),
        migrations.CreateModel(
            name='employer_tb_jobfair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameorg', models.TextField(null='empty')),
                ('rname', models.CharField(max_length=200, null='empty')),
                ('email', models.CharField(max_length=200, null='empty')),
                ('phone', models.CharField(max_length=200, null='empty')),
                ('designation', models.TextField(null='empty')),
                ('address', models.TextField(null='empty')),
                ('website', models.URLField(max_length=500, null='empty')),
                ('job_file', models.FileField(null='empty', upload_to='employer_file')),
                ('date', models.CharField(max_length=200, null='empty')),
            ],
        ),
        migrations.AlterField(
            model_name='admin_tb',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employee_tb',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employer_tb',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
