# Generated by Django 3.2.12 on 2023-12-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220323_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer_tb',
            name='industry',
            field=models.CharField(max_length=200, null='empty'),
            preserve_default='empty',
        ),
    ]
