# Generated by Django 3.2.12 on 2023-12-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_employer_tb_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer_tb_jobfair',
            name='industry',
            field=models.CharField(max_length=200, null='empty'),
            preserve_default='empty',
        ),
    ]
