# Generated by Django 3.2.12 on 2023-12-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_employer_tb_jobfair_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer_tb_jobfair',
            name='company_type',
            field=models.TextField(null='empty'),
            preserve_default='empty',
        ),
        migrations.AddField(
            model_name='employer_tb_jobfair',
            name='organisation',
            field=models.TextField(null='empty'),
            preserve_default='empty',
        ),
        migrations.AddField(
            model_name='employer_tb_jobfair',
            name='profile',
            field=models.TextField(null='empty'),
            preserve_default='empty',
        ),
    ]
