# Generated by Django 3.2.12 on 2023-12-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20231205_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_tb_jobfair',
            name='dob',
            field=models.CharField(max_length=200, null='empty'),
            preserve_default='empty',
        ),
        migrations.AddField(
            model_name='employee_tb_jobfair',
            name='gender',
            field=models.CharField(max_length=200, null='empty'),
            preserve_default='empty',
        ),
        migrations.AddField(
            model_name='employee_tb_jobfair',
            name='maritial',
            field=models.CharField(max_length=200, null='empty'),
            preserve_default='empty',
        ),
        migrations.AddField(
            model_name='employee_tb_jobfair',
            name='place',
            field=models.CharField(max_length=200, null='empty'),
            preserve_default='empty',
        ),
    ]
