# Generated by Django 3.2.12 on 2023-12-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20231205_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_tb_jobfair',
            name='job_option_1',
            field=models.CharField(max_length=200, null='empty'),
            preserve_default='empty',
        ),
        migrations.AddField(
            model_name='employee_tb_jobfair',
            name='job_option_2',
            field=models.CharField(max_length=200, null='empty'),
            preserve_default='empty',
        ),
        migrations.AddField(
            model_name='employee_tb_jobfair',
            name='job_option_3',
            field=models.CharField(max_length=200, null='empty'),
            preserve_default='empty',
        ),
    ]
